apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-vx96b8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vx96b8
  namespace: my-nginx-vx96b8
  labels:
    name: nginx-vx96b8
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-vx96b8
  template:
    metadata:
      namespace: my-nginx-vx96b8
      labels:
        name: nginx-vx96b8
    spec:
      containers:
      - name: nginx-vx96b8
        image: nginx
        ports:
        - containerPort: 80

